CREATE TABLE tasks (
    id INT PRIMARY KEY AUTO_INCREMENT, 
    text VARCHAR(225) NOT NULL, 
    completed_at DATETIME DEFAULT NULL, 
    deleted_at DATETIME DEFAULT NULL, 
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updeted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) DEFAULT CHARSET=utf8;